# Generated by Django 5.0.6 on 2024-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_system", "0003_alter_customeruserprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruserprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_pics"
            ),
        ),
    ]
