# Generated by Django 5.0.6 on 2024-07-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_system", "0006_customeruserprofile_calendar_id_appointment_calendar"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Calendar",
            new_name="CalendarModel",
        ),
    ]
