# Generated by Django 4.2.14 on 2024-07-19 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0009_alter_appointment_date_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
